Create op.yml

diff --git a/op.yml b/op.yml
--- a/op.yml
+++ b/op.yml
@@ -32,7 +32,14 @@ run:
             echo "re-attempting to remove files"
           fi
           i=$((i-1))
-          echo $filesToClean | xargs rm -rf
+          echo $filesToClean | xargs rm -rf > /dev/null
+          if [ $? -eq 0 ]
+          then
+            echo "removing files succeeded"
+            exit 0
+          else
+            echo "removing files failed"
+          fi
         done
     dirs:
       /src: srcDir
