Create op.yml

diff --git a/op.yml b/op.yml
--- a/op.yml
+++ b/op.yml
@@ -22,25 +22,21 @@ run:
         echo 'determining files to clean'
         filesToClean=$(git clean -n $(opts)| sed 's/Would remove *//')
         
-        echo 'removing files'
+        echo 'cleaning files'
         # 2 attempts because for unknown reasons the first regularly fails on osx w/ nfs enabled
         i=2
         while [ $i -gt 0 ]
         do
-          if [ $i -lt 2 ]
-          then
-            echo "re-attempting to remove files"
-          fi
           i=$((i-1))
-          echo $filesToClean | xargs rm -rf > /dev/null
+          for f in $filesToClean; do rm -rf "$f" > /dev/null 2>&1; done
           if [ $? -eq 0 ]
           then
-            echo "removing files succeeded"
+            echo "cleaning files succeeded"
             exit 0
-          else
-            echo "removing files failed"
           fi
         done
+        echo "cleaning files failed"
+        exit 1
     dirs:
       /src: srcDir
     image: { ref: 'opspecpkgs/git.clean:0.0.3' }
